### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by gianmarcoaversanoenx** [lrjconan/GRAN#23]
Running on Google Colab:

```bash
git clone https://github.com/lrjconan/GRAN.git
cd GRAN
pip install -r requirements.txt
```

so far so good. Then:

```bash
python run_exp.py -c config/gran_lobster.yaml
```

I got

```
Traceback (most recent call last):
  File "run_exp.py", line 48, in <module>
    main()
  File "run_exp.py", line 17, in main
    config = get_config(args.config_file, is_test=args.test)
  File "/content/GRAN/utils/arg_helper.py", line 39, in get_config
    config = edict(yaml.load(open(config_file, 'r')))
TypeError: load() missing 1 required positional argument: 'Loader'
```

**Comment by msadat67** [comment]
Hi
you change load to safeload
  config = edict(yaml.safeload(open(config_file, 'r')))

**Comment by gianmarcoaversanoenx** [comment]
Hello
thanks for replying.

Yes, I could find a patch. I just wanted to point out that the source code should be updated with a correction.

Best,
Gianmarco

**Comment by saart** [comment]
For future references: use `config = edict(yaml.safe_load(open(config_file, 'r')))` :)
